version: '3'
services:
  metabase:
    image: metabase/metabase:latest
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_WAIT_FOR_DB=true
    volumes:
      - /metabase-data:/metabase-data
volumes:
  metabase-data:
